### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by RonanKMcGovern** [jzhang38/LongMamba#1]
8x A100 80 GB strikes me as a lot of memory usage for a 2.8 GB model at 16k context.

Is this attributable to the trainable A matrix being large? (owing to the size of h, the state)?

**Comment by jzhang38** [comment]
I am using data parallel training so each GPU takes one 16k context.
> Is this attributable to the trainable A matrix being large? 

Note that I am doing full parameter fintuning. Overall I do not find it uses significantly more memory than a transformer.
